mesos-dns:
  log_driver: ''
  labels:
    io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
  tty: true
  log_opt: {}
  image: rawmind/alpine-mesos-dns:0.6.0
  external_links:
  - ${mesos_zk}:zookeeper
  - ${mesos_master}:master
  environment:
  - MESOS_ZK=zk://zookeeper:2181/mesos
  - MESOS_MASTER=\"master:5050\"
  - MESOS_DNS_DOMAIN=${mesos_domain}

