name: Skydns
description: |
  (Experimental) Skydns 
version: 2.5.3-rancher1
category: Rancher Services
maintainer: "Raul Sanchez <rawmind@gmail.com>"
minimum_rancher_version: v1.11.0
license: 
projectURL: https://github.com/rawmind0/alpine-skydns
